### ISSUE TITLE
Ubuntu 20.10

### ISSUE THREAD

**Issue by DPR-white** [stukev/XPS-17-9700-Ubuntu-Soundfix#2]
Not working for me on 20.10 :/
I'm downgrading to 20.04 LTS. Meh. Wish me luck, please :)

**Comment by DPR-white** [comment]
Oooh fantastic. After many hours of clutching at straws, I FINALLY have it working!
I don't know if it's working purely because of the kernel downgrade, or a combination of that and the change to LTS, or your patch, or all three.
Either way you've been a huge help - I wouldn't have known to switch up the kernel, without your advice! Thank you so much!

For any newcomers to this repo - I'm using kernel 5.6.0-1053-oem, Ubuntu 20.04.02

**Comment by stukev** [comment]
Glad it worked! Thanks for documenting your process.
